spring:
  datasource:
    url: jdbc:h2:mem:testedb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-plataform: org.hibernate.dialect.h2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2